export enum FilmGenre {
  Anime = 'Anime',
  Biographical = 'Biographical',
  ActionMovie = 'ActionMovie',
  WesternFilm = 'WesternFilm',
  Military = 'Military',
  Detective = 'Detective',
  Childrens = 'Childrens',
  Documentary = 'Documentary',
  Drama = 'Drama',
  Historical = 'Historical',
  MovieComic = 'MovieComic',
  Comedy = 'Comedy',
  Concert = 'Concert',
  Short = 'Short',
  Crime = 'Crime',
  Melodrama = 'Melodrama',
  Mystic = 'Mystic',
  Music = 'Music',
  Cartoon = 'Cartoon',
  Musical = 'Musical',
  Scientific = 'Scientific',
  Noir = 'Noir',
  Adventures = 'Adventures',
  RealityShow = 'RealityShow',
  Family = 'Family',
  Sport = 'Sport',
  TalkShow = 'TalkShow',
  Thriller = 'Thriller',
  Horror = 'Horror',
  Fiction = 'Fiction',
  Fantasy = 'Fantasy',
  Erotica = 'Erotica',
}

export const FilmGenreMap: ReadonlyMap<FilmGenre, string> = new Map<
  FilmGenre,
  string
>([
  [FilmGenre.Anime, 'аниме'],
  [FilmGenre.Biographical, 'биографический'],
  [FilmGenre.ActionMovie, 'боевик'],
  [FilmGenre.WesternFilm, 'вестерн'],
  [FilmGenre.Military, 'военный'],
  [FilmGenre.Detective, 'детектив'],
  [FilmGenre.Childrens, 'детский'],
  [FilmGenre.Documentary, 'документальный'],
  [FilmGenre.Drama, 'драма'],
  [FilmGenre.Historical, 'исторический'],
  [FilmGenre.MovieComic, 'кинокомикс'],
  [FilmGenre.Comedy, 'комедия'],
  [FilmGenre.Concert, 'концерт'],
  [FilmGenre.Short, 'короткометражный'],
  [FilmGenre.Crime, 'криминал'],
  [FilmGenre.Melodrama, 'мелодрама'],
  [FilmGenre.Mystic, 'мистика'],
  [FilmGenre.Music, 'музыка'],
  [FilmGenre.Cartoon, 'мультфильм'],
  [FilmGenre.Musical, 'мюзикл'],
  [FilmGenre.Scientific, 'научный'],
  [FilmGenre.Noir, 'нуар'],
  [FilmGenre.Adventures, 'приключения'],
  [FilmGenre.RealityShow, 'реалити-шоу'],
  [FilmGenre.Family, 'семейный'],
  [FilmGenre.Sport, 'спорт'],
  [FilmGenre.TalkShow, 'ток-шоу'],
  [FilmGenre.Thriller, 'триллер'],
  [FilmGenre.Horror, 'ужасы'],
  [FilmGenre.Fiction, 'фантастика'],
  [FilmGenre.Fantasy, 'фэнтези'],
  [FilmGenre.Erotica, 'эротика'],
]);
